import type { StoreListItem } from "../StoresListCard";

export const popularStores: StoreListItem[] = [
  {
    id: 1,
    name: "The Grand Cellar",
    location: "Bandra West, Mumbai",
    image: "/assets/images/banner/store_banner.png",
    amenities: ["Free Wi-Fi", "Free parking", "Dining Table"],
    description: "A curated selection of fine spirits and wines from around the world.",
    storeRating: 4.74,
    deliveryRating: 4.9,
    deliveryAvailable: true,
    isPremium: true,
  },
  {
    id: 2,
    name: "Local Brews & Spirits",
    location: "Koramangala, Bengaluru",
    image: "/assets/images/banner/store_banner.png",
    amenities: ["Free Wi-Fi", "Free parking", "Dining Table"],
    description: "Your neighborhood spot for craft beers and popular local spirits.",
    storeRating: 4.74,
    deliveryRating: 4.9,
    deliveryAvailable: false,
  },
  {
    id: 3,
    name: "Vintage Vintages",
    location: "DLF Phase 4, Gurugram",
    image: "/assets/images/banner/store_banner.png",
    amenities: ["Free Wi-Fi", "Free parking", "Dining Table"],
    description: "Specializing in rare and aged wines, perfect for collectors.",
    storeRating: 4.74,
    deliveryRating: 4.9,
    deliveryAvailable: true,
  },
  {
    id: 4,
    name: "The Bottle Shop",
    location: "Adyar, Chennai",
    image: "/assets/images/banner/store_banner.png",
    amenities: ["Free Wi-Fi", "Free parking", "Dining Table"],
    description: "Your one-stop shop for all your beverage needs, great prices.",
    storeRating: 4.6,
    deliveryRating: 4.5,
    deliveryAvailable: true,
  },
  {
    id: 5,
    name: "Spirits & Co.",
    location: "Jubilee Hills, Hyderabad",
    image: "/assets/images/banner/store_banner.png",
    amenities: ["Free parking", "Dining Table"],
    description: "Premium spirits and cocktail ingredients curated by experts.",
    storeRating: 4.8,
    deliveryRating: 4.7,
    deliveryAvailable: true,
    isPremium: true,
  },
];
